### ISSUE TITLE
buttons double clicking

### ISSUE THREAD

**Issue by thovin** [svenackermann/Prime-Player-Google-Play-Music#124] opened 2015-04-02 19:34 UTC
my pause/play button, as well as the skip song buttons, are double clicking. so when i try to pause or play it does, and then it switches back. i have confirmed that it is not my keyboard keys. i have also tried removing and re-installing the app, to no avail.

**Comment by svenackermann** [comment] 2015-04-07 06:27
Hi,
thanks for your report.
I have no problem with this and no other user did report anything similar, so I guess it's sth. special to your setup.

Typically this is because the action is executed twice on button click (or keyboard shortcut). This could be caused by another extension (maybe the internal miniplayer of Google Music which also has shortcuts) that interferes with Prime Player or for some reason the code of Prime Player can sometimes be executed twice. The latter should get fixed by reloading Google Music (dis-/enabling or reinstalling Prime Player is not enough because Chrome sometimes keeps some artifacts from uninstalled extensions until restart/reload).

You did not mention if you clicked in the miniplayer/toast or used a keyboard shortcut. For keyboard shortcuts there could be other problems, see [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/wiki/Keyboard-shortcuts-explained). You should also try other options to play/pause music (directly in Google Music, miniplayer, toast, keyboard shortcut) to see if it works for them.

Did this happen before or did it suddenly start? Was there some update of Chrome or Prime Player?

**Comment by svenackermann** [comment] 2015-05-20 13:12
closed for inactivity

**Closed by svenackermann** 2015-05-20 13:12 UTC
Labels: user request, wontfix
