### ISSUE TITLE
Resuming playback no longer works

### ISSUE THREAD

**Issue by andyforceno** [svenackermann/Prime-Player-Google-Play-Music#156] opened 2015-10-04 00:18 UTC
Is anyone else having issues with resuming of songs? It used to work most of the time, but now doesn't seem to work at all. Occasionally, GPM will open the last played album (but Prime Player doesn't resume playback), but even this is not consistent. It seems this started around the time of the GPM UI refresh, but I could be wrong about that.

**Comment by andyforceno** [comment] 2015-10-04 00:23
I should mention that I am using Chrome stable version 45.0.2454.101. I usually have my Linux desktop GPM launcher start form https://play.google.com/music/listen?u=0#/recent, but even if I have it start GPM from what appears to be the default url, https://play.google.com/music/listen (which redirects to https://play.google.com/music/listen?u=1#/now), resuming doesn't occur.

I used to launch GPM from the chrome app (not the minipayer thing), but as far as I can tell, that's gone (no longer installed, can't find it on the Chrome Webstore). I assume that just directed the browser to the default address I mentioned above, though.

**Comment by svenackermann** [comment] 2015-10-05 08:27
Hi,

I just checked this but could not reproduce it, everything works fine for me. I could resume the last saved song after going offline and I also could pause/resume the currently playing song.

How you start GPM should not matter. Note that resuming the last saved song is sometimes unstable because it does some error prone actions. First it loads the album for the last song, which should usually work. Then it tries to find the last song on that page, which sometimes need the GPM tab to be visible (check expert option "Make Google Music tab visible when needed"). After it has been found, its play button is clicked and after a second its progess is changed to the last position (also needs the GPM tab to be visible).

Please also note that I do not support the official Google Music app/miniplayer (which you enable/install with the icon in the bottom right corner of GPM). This thing sometimes does some weird stuff that I cannot control and I know that it interferes somehow with Prime Player's functions, there were some reports from users in the past. You should try to uninstall/disable this thing (from chrome://extensions).

**Comment by andyforceno** [comment] 2015-10-05 18:52
I just disabled the miniplayer. I hadn't realized it was enabled (I don't use it). With it disabled, playback still does not resume. There must be something else about my configuration that is interfering. I have the "Make Google Music Tab visible when needed" and "Restore the previously visible tab/window afterwards" options checked.  

I thought maybe the Play Midnight for GPM extension (https://chrome.google.com/webstore/detail/play-midnight-for-google/ljmjmhjkcgfmfdhgplikncgndbdeckci) was interfering with Prime Player, but disabling did not seem to affect playback resuming. It shouldn't interfere anyway, as it just modifies some UI elements of GPM. I'll look into this some more, and if I discover a fix on my end, I'll report back here.

**Comment by okvs** [comment] 2015-10-06 08:38
I have a similar issue with media buttons on OSX (Yosemite). The play/pause button used to work fine (and is in fact the main reason I use this plugin), but has now stopped working.

Fast forward/backward buttons work fine, but when I press pause, there is a tiny hiccough and then playback continues. If I look at the Play Music page I can actually see the the play indicator switching to pause for a fraction of a second.

If I pause the playback using the mouse, I can sometimes resume playback by hitting the media button repeatedly, but that never works for pausing the music.

The media button works fine with e.g. VLC player.

Chrome Version 45.0.2454.101 (64-bit)

**Comment by svenackermann** [comment] 2015-10-07 06:13
This sounds like an old problem that sometimes occurs. The play/pause action is done twice for some reason, so it effectively does nothing.
Restarting Chrome & reloading GPM often solved this problem. But sometimes another extension was doing the same action, so you should try to disable all extension that could interfere with GPM (or possibly change their shortcuts settings). If the problem only occurs with keyboard shortcuts, you should look [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/wiki/Keyboard-shortcuts-explained) to find a possible solution.

I just re-checked, but still have no problems pausing/resuming music with either keyboard shortcuts, miniplayer buttons or toast buttons.

**Comment by okvs** [comment] 2015-10-07 07:16
Ah, yes. I recently installed another Google Play Music extension. Disabling it fixed the problem. Thanks :)

**Comment by andyforceno** [comment] 2015-10-29 14:55
Still no playback resuming for me. Sometimes, when I restart Chrome a GPM tab will open and when it loads, the album I last listened to will load, but the song does not resume. This doesn't help me though, as I typically use GPM in it's own window on a different workspace than my browser. It's not the biggest problem, as now I just have GPM load my recent activity page by default.

**Comment by svenackermann** [comment] 2015-11-03 06:54
So, is that a Chrome/Google issue? Can I close this now?

**Comment by andyforceno** [comment] 2015-11-03 07:16
Yes, go ahead and close it.

**Closed** 2015-11-03 07:16 UTC
Labels: bug, need-feedback, user request
