### ISSUE TITLE
Song title missing in detached player

### ISSUE THREAD

**Issue by 70melbatoast** [svenackermann/Prime-Player-Google-Play-Music#162] opened 2015-12-10 12:32 UTC
With the 3.7 update, the song title is missing in the player and also with the new option of displaying the song in the title bar. Album art is also missing. Artist and album only display in both. Using Chrome 47.0.2526.80 on a Windows 7 machine. Keep the awesome work! Great player!

**Comment by svenackermann** [comment] 2015-12-10 12:36
Hi, thanks for the report.
This has been caused by a change on the Google page. It's already fixed with 3.7.1, but this release is still waiting for approval by Google. Normally after uploading a new version it takes about 2-3 hours to be approved, but for some reason this time it takes much longer.

**Closed by svenackermann** 2015-12-10 12:36 UTC
Labels: bug, googlechange, user request
